EMOJI = {
    'BORDER': '🌳',
    'CABIN': '🏠',
    'CANOE': '🛶',
    'COBWEB': '🕸️ ',
    'DOOR': '🚪',
    'DOORKEY': '🗝️',
    'GRAVE': '🪦',
    'GOLDKEY': '🔑',
    'EMPTY': '⬛️',
    'FIELD': '🌾',
    'GRAVE': '🪦',
    'HUMAN': '🏃',
    'KNIFE': '🔪',
    'LIGHT': '🔦',
    'LINK': '🔗',
    'LOCK': '🔒',
    'ROCK': '🪨',
    'SAVED': '🚔',
    'SNAKE': '🐍',
    'SPIDER': '🕷️ ',
    'TREE': '🌳',
    'WATER': '🌊',
    'WINDOW': '🪟',
    'WOLF': '🐺',
    'WEEDS': '🌾',
    'WOODS': '🌲',
    'WRECKED': '🏚️'
}
